[package]
name = "hello"
version = "0.1.0"
edition = "2021"
default-run = "hello"

[dependencies]

[dev-dependencies]
assert_cmd = "2"

# See more keys and their definitions at 
# https://doc.rust-lang.org/cargo/reference/manifest.html

